spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: test_pswd
    url: jdbc:postgresql://3.141.172.59:5432/test_db?&useUnicode=true&characterEncoding=utf8
  jpa:
    hibernate:
    show-sql: true
    
logging:
  level: 
    root: warn
    com.syngenta.lawnngarden: info
  file: log/app-pro.log


server:
  port: 8081
  