spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: test_pswd
    url: jdbc:postgresql://3.141.172.59:5432/test_db?&useUnicode=true&characterEncoding=utf8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
logging:
  level: 
    root: info
    com.syngenta.lawnngarden: debug
  file:
    name: ./log/app-pro.log
    
